### ISSUE TITLE
Mark as deprecated?

### ISSUE THREAD

**Issue by alecgibson** [share/sharedb-postgres#11]
This library hasn't had any updates since March 2018. We're thinking of officially linking out to a [fork](https://github.com/plotdb/sharedb-postgres) in the [ShareDB docs](https://github.com/share/sharedb/pull/452/files).

@nornagon do you have any desire/capacity to keep this library updated? If not, we should go ahead and mark this as deprecated in the `README`, probably with a link out to the actively-maintained fork.

**Comment by dustin-weber-REISys** [comment]
That would be really helpful. I was working on using postgres and was stuck trying to use this one. I switched to the fork linked above and got it working very quickly.

**Comment by nornagon** [comment]
Missed this issue somehow! I'm happy to hand over maintainership of this library; I'm no longer using it. Perhaps @zbryikt or someone else would like to put their hand up for it?

**Comment by alecgibson** [comment]
@nornagon I'm happy to look after it for now until someone else more suitable can take ownership. Maybe also @ericyhwang ? (We're still having weekly ShareDB meetings)

**Comment by nornagon** [comment]
@alecgibson I added you as an admin for this repo and invited you as a maintainer for the npm package. Let me know if there's anything else I can give you access to!

**Comment by alecgibson** [comment]
Thanks!

**Comment by alecgibson** [comment]
@zbryikt would you have any interest in maintaining this? We could catch this repo up to your fork?

**Comment by zbryikt** [comment]
hi guys! My main concern about maintaining this is that I'm not quite familiar with the original code, to the extent that it's better if someone can review my code when I make any changes.

But indeed we are still using it thus will want to help fix bugs in the future. Currently this library is kinda stable so not sure if another maintainer is the most important thing, perhaps we can first update the original repo based on the fork?

The fork is based on this repo and released under the same license so please feel free to use any of the update in it. :)

**Comment by alecgibson** [comment]
Okay great will try to catch up in this PR https://github.com/share/sharedb-postgres/pull/14

Will discuss with @ericyhwang next week; I'm sure we can at least review PRs, etc.

**Comment by curran** [comment]
I'm looking at potentially migrating from MongoDB to Postgres and am also curious about the status of this repo.

We have:
 * https://github.com/plotdb/sharedb-postgres, which is 5 commits ahead, 1 commit behind zbryikt:master
 * https://github.com/zbryikt/sharedb-postgres-jsonb , which is marked as deprecated and points to plotdb/sharedb-postgres
 * This repo https://github.com/share/sharedb-postgres, which describes itself as though it is plotdb/sharedb-postgres .

Interesting stuff here, looks like there were active forks with some updates that could maybe get pulled in: https://github.com/share/sharedb-postgres/network

Looks to me like this repo we're on now is the latest and greatest. The README needs some love so it doesn't read as though it's the PlotDB fork.

**Comment by zbryikt** [comment]
Yes, I think alecgibson has merged the update in [plotdb/sharedb-postgres](https://github.com/plotdb/sharedb-postgres) so we should consider this repo as the official and best to go for posgres-sharedb integration; yet I didn't notice that the README from PlotDB got merged too so perhaps we only need a simple update in README to make it look like the official one. :)

**Comment by curran** [comment]
I took a stab at the README update.

I also noticed the package name in `package.json` may need to be updated and make an issue for that - #20

**Comment by alecgibson** [comment]
Okay trying to give this repo some love.

Have just released https://github.com/share/sharedb-postgres/releases/tag/v4.1.0 which releases the fork merge and adds support for recent `sharedb` versions.

I'm also working on adding CI in https://github.com/share/sharedb-postgres/pull/24 — should hopefully lead to a major version bump soon that brings this library fully up to spec with the upstream DB adapter tests.

**Comment by curran** [comment]
Amazing! Thank you so much for this work. I love the idea of using ShareDB on Postgres.
