### ISSUE TITLE
Change Package Name

### ISSUE THREAD

**Issue by curran** [share/sharedb-postgres#20]
Currently the name in `package.json` is `@plotdb/sharedb-postgres`.

Perhaps that could be changed to `sharedb-postgres`.

**Comment by curran** [comment]
https://www.npmjs.com/package/sharedb-postgres points here, last published 3 years ago.

I say let's get some tests running, upgrade dependencies, and re-publish this thing!

**Comment by alecgibson** [comment]
Fixed the name in https://github.com/share/sharedb-postgres/pull/22
