### ISSUE TITLE
Getting setup

### ISSUE THREAD

**Issue by yarnball** [share/sharedb-postgres#7]
Hi,

You mention that this `Doesn't support queries (yet?).`. Does that mean it won't work with `ShareDB` queriers (like updating/modifying objects)?

Also, can you provide more detail on setting up? 

I  get the error: `query DB method unimplemented`

**Comment by alecgibson** [comment]
This adapter can use ShareDB by fetching individual `Doc`s by ID, but not by using the ShareDB [Query](https://share.github.io/sharedb/queries), which is why you're getting that error.

Closing as stale. Please reopen if you have further questions.
