### ISSUE TITLE
What's the purpose of the op-table?

### ISSUE THREAD

**Issue by buffpojken** [share/sharedb-postgres#9]
Sorry if this is the inappropriate place for this question - but what's the purpose of the op-table?

As far as I can tell, the snapshot-table contains everything needed to maintain a proper, conflict-managed version of a given document? Is the op-table for history-purposes like replay, undo/redo or similar?

**Comment by alecgibson** [comment]
The op table is needed to resolve conflicts, since out-of-date inflight ops need to be transformed against other ops that have been committed. It's also used to catch old clients up to the current version without sending the whole snapshot.
